### ISSUE TITLE
?actionBarTheme not set correctly

### ISSUE THREAD

**Issue by NoodleMage** [jaredrummler/Cyanea#32]
In our app we use NoActionBar theme and include the toolbar in our layout (Theme.Cyanea.Light.NoActionBar).

e.g. https://github.com/NoodleMage/tachiyomi/blob/cyanea_impl/ui/src/main/res/layout/catalogs_controller.xml

The problem is that app:theme=?actionBarTheme doesn't seem to update the toolbar to the correct color if NoActionBar is used so the title text color stays black.

![screenshot_1543761509](https://user-images.githubusercontent.com/9655378/49341064-8ab50f00-f648-11e8-9185-83cc703f5a45.png)

**Comment by jaredrummler** [comment]
Fixed in 1.0.1

**Comment by nathanRamaNoodles** [comment]
This doesn't work for fragments.  If the toolbar is included with the fragment, then the title's text color always stays black. 

 Also, I have another similar issue with the textView staying the same black color in a navigation drawer header.

**My solution**:  There needs to be a way to force this black/white textColor programmatically depending on the background. That would be a nice feature 😊.
