### ISSUE TITLE
Color applied incorrectly

### ISSUE THREAD

**Issue by xDragonZ** [jaredrummler/Cyanea#37]
While implementing and testing around, I found out that sometimes colors are applied incorrectly and it required clear app data to reset it. Sometimes force stop app will help, sometimes it require clear app data.

Noticed that the color accent applied to TextView/CardView/ActionBar title where it shouldn't.

**Tested on:** normal device and emulator, android 9.0 and 8.0 with v1.0.1 library

Comparing the "normal" pref xml (com.jaredrummler.cyanea) and "incorrect" xml, found out `accent_light` and `accent_dark` values is different.

Not sure is related to pref commit is having race condition or the activity recreated and wrong color applied.

I decided to test on the demo app that downloaded directly from here, which also the same results.

![image](https://user-images.githubusercontent.com/951083/49827634-bfe9fb80-fdc4-11e8-8a10-f3da58fc79b2.png)

![image](https://user-images.githubusercontent.com/951083/49827632-bb254780-fdc4-11e8-9c65-f2a121f88e46.png)

Video: https://file.io/GEztLq or https://upload.cat/88665821462cd5ed

**Comment by jaredrummler** [comment]
Interesting! From the video, it looks pretty hard to reproduce. Hopefully we can get reproduction steps. This might have to do with the primary text color being equivalent to the accent or primary color.

**Comment by xDragonZ** [comment]
Is it related to the if-else detecting for the dark color giving the problem?

**Comment by xDragonZ** [comment]
Any updates on this?

**Comment by stavangr** [comment]
I was able to reproduce this issue. As a workaround I removed cyanea_primary_reference from my colors.xml

**Comment by xDragonZ** [comment]
@jaredrummler  it will be great if you can tag current changes to new version (1.0.2) and release it.

**Comment by xDragonZ** [comment]
@jaredrummler it will be great if you can tag current changes to new version (1.0.2) and release it.

**Comment by xDragonZ** [comment]
still no update since last year :(

**Comment by jrcacd** [comment]
Any updates on this?

**Comment by xDragonZ** [comment]
Any updates on this?

**Comment by xDragonZ** [comment]
Hi, any updates on this?

**Comment by xDragonZ** [comment]
Can you provide me owner access to this repo so that I could push latest fix for you

**Comment by ricrebelo** [comment]
Having the same issue, the workarround provided by @stavangr doesnt seem to work for me.

**Comment by XuanRan0808** [comment]
I meeting the same problem,so i want to know the error solve.But now i see the issue still is open ,the dev still not fix?
